version: "3.9"

services:
  frontend:
    image: mfs-frontend-image:latest
    container_name: mfs-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend

  backend:
    image: mfs-backend-image:latest
    container_name: mfs-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      AMAZON_REFRESH_TOKEN: ${AMAZON_REFRESH_TOKEN}
      AMAZON_CLIENT_ID: ${AMAZON_CLIENT_ID}
      AMAZON_CLIENT_SECRET: ${AMAZON_CLIENT_SECRET}
      AMAZON_PROFILE_ID: ${AMAZON_PROFILE_ID}
    depends_on:
      - db
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
